const en = {
  app: { title: 'SupplyFlow', subtitle: 'Business Process Management System' },
  nav: { dashboard: 'Dashboard', orders: 'Orders', inventory: 'Inventory', customers: 'Customers', complaints: 'Complaints', reports: 'Reports', ai: 'AI Predictions', admin: 'Admin' },
  auth: { login: 'Login', register: 'Register', logout: 'Logout', email: 'Email', password: 'Password', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', title: 'Login to SupplyFlow', fullName: 'Full Name', role: 'Role', submit: 'Submit', passwordPlaceholder: 'Enter your password', loginError: 'Login failed', registerTitle: 'Register', fullNameLabel: 'Full Name', fullNamePlaceholder: 'Enter your full name', registerSuccess: 'Registration Successful', registerSuccessMsg: 'Account created successfully. Please log in.', registerError: 'Registration failed', admin: 'Admin', manager: 'Manager', warehouse: 'Warehouse' },
  theme: { light: 'Light', dark: 'Dark' },
  lang: { kk: 'Қазақша', ru: 'Русский', en: 'English' },
  common: { loading: 'Loading...', error: 'An error occurred', errorUnknown: 'Unknown error', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', create: 'Create', search: 'Search', noData: 'No data', export: 'Export', filter: 'Filter', status: 'Status', actions: 'Actions', success: 'Success', add: 'Add', back: 'Back', notFound: 'Not found', clear: 'Clear', refresh: 'Refresh', retry: 'Retry' },
  dashboard: { title: "Today's Overview", todayOrders: "Today's Orders", todayRevenue: "Today's Revenue", pendingOrders: 'Pending Orders', inventoryAccuracy: 'Inventory Accuracy', dailyOrders: 'Daily Orders', orderStatusBreakdown: 'Order Status Breakdown', revenueTrend: 'Revenue Trend', topProducts: 'Top Products', quantity: 'Quantity', revenue: 'Revenue' },
  order: { title: 'Orders', create: 'New Order', id: 'ID', customer: 'Customer', amount: 'Amount', address: 'Address', date: 'Date', view: 'View', cancel: 'Cancel', noOrders: 'No orders', selectCustomer: 'Select customer', selectProduct: 'Select product', addProduct: 'Add product', products: 'Products', deliveryAddress: 'Delivery Address', enterAddress: 'Enter address', deadline: 'Deadline', selectDeadline: 'Select deadline', notes: 'Notes', optionalInfo: 'Additional info (optional)', createOrder: 'Create Order', successCreated: 'Order created', successCancelled: 'Order cancelled', successUpdated: 'Status updated', detail: 'Order #', orderInfo: 'Order Information', items: 'Items', totalAmount: 'Total Amount', costAmount: 'Cost Amount', noItems: 'No items', changeStatus: 'Change Status', pickList: 'Pick List', pickListEmpty: 'No pick list data', location: 'Location', notFound: 'Order not found', createdDate: 'Created Time', statuses: { Pending: 'Pending', Confirmed: 'Confirmed', Processing: 'Processing', Shipped: 'Shipped', Delivered: 'Delivered', Cancelled: 'Cancelled' } },
  inventory: { title: 'Inventory', products: 'Products', priority: 'Priority', alerts: 'Alerts', logs: 'Logs', name: 'Name', sku: 'SKU', stock: 'Stock', reserved: 'Reserved', available: 'Available', adjust: 'Adjust', reserve: 'Reserve', realtime: 'Real-time', offline: 'Offline', adjustStock: 'Adjust Stock', reservePriority: 'Reserve Priority', noAlerts: 'No alerts', category: 'Category', price: 'Price', noProducts: 'No products', reserveByPriority: 'Reserve by Priority', loadData: 'Load data', noPriorityData: 'No priority data', loadPriorityData: 'Click button to load data', changeAmount: 'Change amount (+/-)', exampleChange: 'E.g.: 10 or -5', reason: 'Reason', enterReason: 'Enter reason for adjustment', successAdjusted: 'Stock adjusted', selectProduct: 'Select product', customer: 'Customer', hours: 'h', requested: 'Requested', possible: 'Possible?', canFulfill: 'Yes', cannotFulfill: 'No', margin: 'Margin', orderNum: 'Order #' },
  customer: { title: 'Customers', company: 'Company', contact: 'Contact Person', phone: 'Phone', email: 'Email', tier: 'Tier', newCustomer: 'New Customer', totalOrders: 'Total Orders', lastOrder: 'Last Order', noCustomers: 'No customers', editCustomer: 'Edit Customer', companyName: 'Company Name', phoneNumber: 'Phone Number', contactPerson: 'Contact Person', successCreated: 'Customer created', successUpdated: 'Customer updated', notFound: 'Customer not found', info: 'Customer Information', createdDate: 'Created Date', orderHistory: 'Order History', contactLog: 'Contact Log', complaints: 'Complaints', noOrders: 'No orders', noContactLogs: 'No contact logs', noComplaints: 'No complaints', newContactLog: 'New Note', contactLogPlaceholder: 'Note text', addComplaint: 'Add Complaint', newComplaint: 'New Complaint', complaintTitle: 'Title', complaintDesc: 'Description' },
  complaint: { title: 'Complaint Management', newComplaint: 'New Complaint', id: 'ID', customer: 'Customer', fieldTitle: 'Title', description: 'Description', status: 'Status', date: 'Date', actions: 'Actions', noComplaints: 'No complaints', selectCustomer: 'Select customer', complaintTitle: 'Complaint title', complaintDesc: 'Complaint description', successCreated: 'Complaint created', successUpdated: 'Status updated', changeStatus: 'Change Complaint Status', edit: 'Edit', add: 'Add', save: 'Save', statuses: { Open: 'Open', InProgress: 'In Progress', Resolved: 'Resolved' } },
  report: { title: 'Reports', dashboard: 'Dashboard', exportExcel: 'Excel', exportPdf: 'PDF', exportCsv: 'CSV', filters: 'Filters', dateFrom: 'Date From', dateTo: 'Date To', filterStatus: 'Status', filterCustomer: 'Customer', applyFilter: 'Apply Filter', exportSuccess: 'Report downloaded in {format} format', allStatuses: 'All', noReports: 'No reports' },
  ai: { title: 'AI Predictions', forecast: 'Demand Forecast', anomalies: 'Anomalies', product: 'Product', avgSales: 'Avg Monthly Sales', predicted: 'Predicted Demand', reorder: 'Recommended Order', refreshForecast: 'Refresh Forecast', forecastChart: 'Demand Forecast & Current Stock', currentStock: 'Current Stock', predictedDemand: 'Predicted Demand', noForecasts: 'No forecasts', noAnomalies: 'No anomalies' },
  admin: { title: 'Admin Panel', users: 'Users', config: 'Configuration', logs: 'System Logs', addUser: 'Add User', id: 'ID', email: 'Email', fullName: 'Full Name', role: 'Role', createdDate: 'Created Date', actions: 'Actions', changeRole: 'Change Role', changeRoleFor: 'User', newRole: 'New Role', noUsers: 'No users', betaLabel: 'Beta Value', companyName: 'Company Name', save: 'Save', successCreated: 'User created', successRole: 'Role updated', successConfig: 'Configuration saved', error: 'An error occurred', time: 'Time', user: 'User', action: 'Action', details: 'Details', noLogs: 'No log entries', password: 'Password', add: 'Add' },
  health: { status: 'Status', uptime: 'Uptime', memory: 'Memory', database: 'Database' },
  notification: { success: 'Success', error: 'Error' },
};
export default en;
