const kk = {
  app: { title: 'SupplyFlow', subtitle: 'Бизнес процестерді басқару жүйесі' },
  nav: { dashboard: 'Бақылау тақтасы', orders: 'Тапсырыстар', inventory: 'Қойма', customers: 'Клиенттер', complaints: 'Шағымдар', reports: 'Есептер', ai: 'ЖИ болжамдар', admin: 'Админ' },
  auth: { login: 'Кіру', register: 'Тіркелу', logout: 'Шығу', email: 'Электронды пошта', password: 'Құпия сөз', noAccount: 'Аккаунтыңыз жоқ па?', hasAccount: 'Аккаунтыңыз бар ма?', title: 'SupplyFlow жүйесіне кіру', fullName: 'Аты-жөні', role: 'Рөл', submit: 'Жіберу', passwordPlaceholder: 'Құпия сөзіңізді енгізіңіз', loginError: 'Кіру кезінде қате орын алды', registerTitle: 'Тіркелу', fullNameLabel: 'Толық аты-жөні', fullNamePlaceholder: 'Аты-жөніңізді енгізіңіз', registerSuccess: 'Сәтті тіркелу', registerSuccessMsg: 'Аккаунтыңыз сәтті құрылды. Жүйеге кіріңіз.', registerError: 'Тіркелу кезінде қате орын алды', admin: 'Админ', manager: 'Менеджер', warehouse: 'Қоймашы' },
  theme: { light: 'Жарық', dark: 'Қараңғы' },
  lang: { kk: 'Қазақша', ru: 'Русский', en: 'English' },
  common: { loading: 'Жүктелуде...', error: 'Қате орын алды', errorUnknown: 'Белгісіз қате', save: 'Сақтау', cancel: 'Болдырмау', delete: 'Жою', edit: 'Өңдеу', create: 'Жасау', search: 'Іздеу', noData: 'Деректер жоқ', export: 'Экспорт', filter: 'Сүзгі', status: 'Статус', actions: 'Әрекеттер', success: 'Сәтті', add: 'Қосу', back: 'Артқа', notFound: 'Табылмады', clear: 'Тазалау', refresh: 'Жаңарту', retry: 'Қайталау' },
  dashboard: { title: 'Бүгінгі шолу', todayOrders: 'Бүгінгі тапсырыстар', todayRevenue: 'Бүгінгі кіріс', pendingOrders: 'Күтілетін тапсырыстар', inventoryAccuracy: 'Қойма дәлдігі', dailyOrders: 'Күнделікті тапсырыстар', orderStatusBreakdown: 'Тапсырыс күйі бойынша бөлініс', revenueTrend: 'Кіріс динамикасы', topProducts: 'Үздік өнімдер', quantity: 'Саны', revenue: 'Кіріс' },
  order: { title: 'Тапсырыстар', create: 'Жаңа тапсырыс', id: 'ID', customer: 'Клиент', amount: 'Сома', address: 'Мекен-жай', date: 'Күні', view: 'Қарау', cancel: 'Бас тарту', noOrders: 'Тапсырыстар жоқ', selectCustomer: 'Клиентті таңдаңыз', selectProduct: 'Өнімді таңдаңыз', addProduct: 'Өнім қосу', products: 'Өнімдер', deliveryAddress: 'Жеткізу мекенжайы', enterAddress: 'Мекенжайды енгізіңіз', deadline: 'Мерзім', selectDeadline: 'Мерзімді таңдаңыз', notes: 'Ескертпелер', optionalInfo: 'Қосымша ақпарат (міндетті емес)', createOrder: 'Тапсырыс жасау', successCreated: 'Тапсырыс жасалды', successCancelled: 'Тапсырыс болдырылмады', successUpdated: 'Күй жаңартылды', detail: 'Тапсырыс #', orderInfo: 'Тапсырыс ақпараты', items: 'Тауарлар', totalAmount: 'Жалпы сома', costAmount: 'Өзіндік құн', noItems: 'Тауарлар жоқ', changeStatus: 'Күйді өзгерту', pickList: 'Пик-парақ', pickListEmpty: 'Пик-парақ деректері жоқ', location: 'Орналасуы', notFound: 'Тапсырыс табылмады', createdDate: 'Құрылған уақыт', statuses: { Pending: 'Күтілуде', Confirmed: 'Расталған', Processing: 'Өңделуде', Shipped: 'Жөнелтілген', Delivered: 'Жеткізілген', Cancelled: 'Бас тартылған' } },
  inventory: { title: 'Қойма', products: 'Өнімдер', priority: 'Басымдық', alerts: 'Ескертулер', logs: 'Журнал', name: 'Аты', sku: 'SKU', stock: 'Қор', reserved: 'Резервтелген', available: 'Қолжетімді', adjust: 'Түзету', reserve: 'Резервтеу', realtime: 'Нақты уақыт', offline: 'Офлайн', adjustStock: 'Қорды түзету', reservePriority: 'Резервтеу приоритеті', noAlerts: 'Ескертулер жоқ', category: 'Санаты', price: 'Бағасы', noProducts: 'Өнімдер жоқ', reserveByPriority: 'Приоритет бойынша резервтеу', loadData: 'Деректерді жүктеу', noPriorityData: 'Приоритет деректері жоқ', loadPriorityData: 'Деректерді жүктеу үшін батырманы басыңыз', changeAmount: 'Өзгеріс мөлшері (+/-)', exampleChange: 'Мысалы: 10 немесе -5', reason: 'Себебі', enterReason: 'Түзету себебін енгізіңіз', successAdjusted: 'Қор түзетілді', selectProduct: 'Өнімді таңдаңыз', customer: 'Клиент', hours: 'сағ', requested: 'Сұралған', possible: 'Мүмкін бе?', canFulfill: 'Иә', cannotFulfill: 'Жоқ', margin: 'Маржа', orderNum: 'Тапсырыс #' },
  customer: { title: 'Клиенттер', company: 'Компания', contact: 'Байланыс тұлға', phone: 'Телефон', email: 'Email', tier: 'Деңгей', newCustomer: 'Жаңа клиент', totalOrders: 'Тапсырыстар саны', lastOrder: 'Соңғы тапсырыс', noCustomers: 'Клиенттер жоқ', editCustomer: 'Клиентті өңдеу', companyName: 'Компания атауы', phoneNumber: 'Телефон нөмірі', contactPerson: 'Байланыс тұлға', successCreated: 'Клиент қосылды', successUpdated: 'Клиент жаңартылды', notFound: 'Клиент табылмады', info: 'Клиент ақпараты', createdDate: 'Құрылған уақыт', orderHistory: 'Тапсырыс тарихы', contactLog: 'Байланыс журналы', complaints: 'Шағымдар', noOrders: 'Тапсырыстар жоқ', noContactLogs: 'Байланыс жазбалары жоқ', noComplaints: 'Шағымдар жоқ', newContactLog: 'Жаңа жазба', contactLogPlaceholder: 'Жазба мәтіні', addComplaint: 'Шағым қосу', newComplaint: 'Жаңа шағым', complaintTitle: 'Тақырыбы', complaintDesc: 'Сипаттамасы' },
  complaint: { title: 'Шағымдарды басқару', newComplaint: 'Жаңа шағым', id: 'ID', customer: 'Клиент', fieldTitle: 'Тақырып', description: 'Сипаттама', status: 'Күй', date: 'Күні', actions: 'Әрекеттер', noComplaints: 'Шағымдар жоқ', selectCustomer: 'Клиентті таңдаңыз', complaintTitle: 'Шағым тақырыбы', complaintDesc: 'Шағым сипаттамасы', successCreated: 'Шағым қосылды', successUpdated: 'Күй жаңартылды', changeStatus: 'Шағым күйін өзгерту', edit: 'Өңдеу', add: 'Қосу', save: 'Сақтау', statuses: { Open: 'Ашық', InProgress: 'Орындалуда', Resolved: 'Шешілген' } },
  report: { title: 'Есептер', dashboard: 'Бақылау тақтасы', exportExcel: 'Excel', exportPdf: 'PDF', exportCsv: 'CSV', filters: 'Сүзгілер', dateFrom: 'Басталу күні', dateTo: 'Аяқталу күні', filterStatus: 'Күй', filterCustomer: 'Клиент', applyFilter: 'Сүзгілеу', exportSuccess: 'Есеп {format} форматында жүктелді', allStatuses: 'Барлығы', noReports: 'Есептер жоқ' },
  ai: { title: 'ЖИ болжамдар', forecast: 'Сұраныс болжамы', anomalies: 'Аномалиялар', product: 'Өнім', avgSales: 'Орт. айлық сату', predicted: 'Болжам', reorder: 'Ұсынылатын тапсырыс', refreshForecast: 'Болжамды жаңарту', forecastChart: 'Сұраныс болжамы және ағымдағы қор', currentStock: 'Ағымдағы қор', predictedDemand: 'Болжамды сұраныс', noForecasts: 'Болжамдар жоқ', noAnomalies: 'Аномалиялар жоқ' },
  admin: { title: 'Админ панелі', users: 'Пайдаланушылар', config: 'Конфигурация', logs: 'Жүйе журналы', addUser: 'Пайдаланушы қосу', id: 'ID', email: 'Email', fullName: 'Аты-жөні', role: 'Рөлі', createdDate: 'Құрылған күні', actions: 'Әрекеттер', changeRole: 'Рөлді өзгерту', changeRoleFor: 'Пайдаланушы', newRole: 'Жаңа рөл', noUsers: 'Пайдаланушылар жоқ', betaLabel: 'Beta мәні', companyName: 'Компания атауы', save: 'Сақтау', successCreated: 'Пайдаланушы қосылды', successRole: 'Рөл жаңартылды', successConfig: 'Конфигурация сақталды', error: 'Қате орын алды', time: 'Уақыты', user: 'Пайдаланушы', action: 'Әрекет', details: 'Мәлімет', noLogs: 'Журнал жазбалары жоқ', password: 'Құпия сөз', add: 'Қосу' },
  health: { status: 'Статус', uptime: 'Жұмыс уақыты', memory: 'Жад', database: 'Дерекқор' },
  notification: { success: 'Сәтті', error: 'Қате' },
};
export default kk;
