const ru = {
  app: { title: 'SupplyFlow', subtitle: 'Система управления бизнес-процессами' },
  nav: { dashboard: 'Панель управления', orders: 'Заказы', inventory: 'Склад', customers: 'Клиенты', complaints: 'Жалобы', reports: 'Отчеты', ai: 'ИИ прогнозы', admin: 'Админ' },
  auth: { login: 'Вход', register: 'Регистрация', logout: 'Выход', email: 'Электронная почта', password: 'Пароль', noAccount: 'Нет аккаунта?', hasAccount: 'Есть аккаунт?', title: 'Вход в SupplyFlow', fullName: 'ФИО', role: 'Роль', submit: 'Отправить', passwordPlaceholder: 'Введите ваш пароль', loginError: 'Ошибка при входе', registerTitle: 'Регистрация', fullNameLabel: 'Полное имя', fullNamePlaceholder: 'Введите ваше имя', registerSuccess: 'Успешная регистрация', registerSuccessMsg: 'Аккаунт успешно создан. Войдите в систему.', registerError: 'Ошибка при регистрации', admin: 'Админ', manager: 'Менеджер', warehouse: 'Кладовщик' },
  theme: { light: 'Светлая', dark: 'Темная' },
  lang: { kk: 'Қазақша', ru: 'Русский', en: 'English' },
  common: { loading: 'Загрузка...', error: 'Произошла ошибка', errorUnknown: 'Неизвестная ошибка', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить', create: 'Создать', search: 'Поиск', noData: 'Нет данных', export: 'Экспорт', filter: 'Фильтр', status: 'Статус', actions: 'Действия', success: 'Успешно', add: 'Добавить', back: 'Назад', notFound: 'Не найдено', clear: 'Очистить', refresh: 'Обновить', retry: 'Повторить' },
  dashboard: { title: 'Обзор за сегодня', todayOrders: 'Заказы сегодня', todayRevenue: 'Доход сегодня', pendingOrders: 'Ожидаемые заказы', inventoryAccuracy: 'Точность склада', dailyOrders: 'Ежедневные заказы', orderStatusBreakdown: 'Распределение по статусам', revenueTrend: 'Динамика доходов', topProducts: 'Лучшие товары', quantity: 'Кол-во', revenue: 'Доход' },
  order: { title: 'Заказы', create: 'Новый заказ', id: 'ID', customer: 'Клиент', amount: 'Сумма', address: 'Адрес', date: 'Дата', view: 'Просмотр', cancel: 'Отменить', noOrders: 'Нет заказов', selectCustomer: 'Выберите клиента', selectProduct: 'Выберите товар', addProduct: 'Добавить товар', products: 'Товары', deliveryAddress: 'Адрес доставки', enterAddress: 'Введите адрес', deadline: 'Срок', selectDeadline: 'Выберите срок', notes: 'Заметки', optionalInfo: 'Доп. информация (необязательно)', createOrder: 'Создать заказ', successCreated: 'Заказ создан', successCancelled: 'Заказ отменен', successUpdated: 'Статус обновлен', detail: 'Заказ #', orderInfo: 'Информация о заказе', items: 'Товары', totalAmount: 'Общая сумма', costAmount: 'Себестоимость', noItems: 'Нет товаров', changeStatus: 'Изменить статус', pickList: 'Пик-лист', pickListEmpty: 'Нет данных пик-листа', location: 'Расположение', notFound: 'Заказ не найден', createdDate: 'Время создания', statuses: { Pending: 'Ожидание', Confirmed: 'Подтвержден', Processing: 'В обработке', Shipped: 'Отправлен', Delivered: 'Доставлен', Cancelled: 'Отменен' } },
  inventory: { title: 'Склад', products: 'Товары', priority: 'Приоритет', alerts: 'Уведомления', logs: 'Журнал', name: 'Название', sku: 'SKU', stock: 'Запас', reserved: 'Зарезервировано', available: 'Доступно', adjust: 'Корректировка', reserve: 'Резерв', realtime: 'Реальное время', offline: 'Офлайн', adjustStock: 'Корректировка запасов', reservePriority: 'Приоритет резервирования', noAlerts: 'Нет уведомлений', category: 'Категория', price: 'Цена', noProducts: 'Нет товаров', reserveByPriority: 'Резервировать по приоритету', loadData: 'Загрузить данные', noPriorityData: 'Нет данных приоритета', loadPriorityData: 'Нажмите кнопку для загрузки данных', changeAmount: 'Величина изменения (+/-)', exampleChange: 'Например: 10 или -5', reason: 'Причина', enterReason: 'Введите причину корректировки', successAdjusted: 'Запас скорректирован', selectProduct: 'Выберите товар', customer: 'Клиент', hours: 'ч', requested: 'Запрошено', possible: 'Возможно?', canFulfill: 'Да', cannotFulfill: 'Нет', margin: 'Маржа', orderNum: 'Заказ #' },
  customer: { title: 'Клиенты', company: 'Компания', contact: 'Контактное лицо', phone: 'Телефон', email: 'Email', tier: 'Уровень', newCustomer: 'Новый клиент', totalOrders: 'Кол-во заказов', lastOrder: 'Последний заказ', noCustomers: 'Нет клиентов', editCustomer: 'Редактировать клиента', companyName: 'Название компании', phoneNumber: 'Номер телефона', contactPerson: 'Контактное лицо', successCreated: 'Клиент добавлен', successUpdated: 'Клиент обновлен', notFound: 'Клиент не найден', info: 'Информация о клиенте', createdDate: 'Дата создания', orderHistory: 'История заказов', contactLog: 'Журнал контактов', complaints: 'Жалобы', noOrders: 'Нет заказов', noContactLogs: 'Нет записей контактов', noComplaints: 'Нет жалоб', newContactLog: 'Новая запись', contactLogPlaceholder: 'Текст записи', addComplaint: 'Добавить жалобу', newComplaint: 'Новая жалоба', complaintTitle: 'Заголовок', complaintDesc: 'Описание' },
  complaint: { title: 'Управление жалобами', newComplaint: 'Новая жалоба', id: 'ID', customer: 'Клиент', fieldTitle: 'Заголовок', description: 'Описание', status: 'Статус', date: 'Дата', actions: 'Действия', noComplaints: 'Нет жалоб', selectCustomer: 'Выберите клиента', complaintTitle: 'Заголовок жалобы', complaintDesc: 'Описание жалобы', successCreated: 'Жалоба добавлена', successUpdated: 'Статус обновлен', changeStatus: 'Изменить статус жалобы', edit: 'Изменить', add: 'Добавить', save: 'Сохранить', statuses: { Open: 'Открыто', InProgress: 'В работе', Resolved: 'Решено' } },
  report: { title: 'Отчеты', dashboard: 'Панель управления', exportExcel: 'Excel', exportPdf: 'PDF', exportCsv: 'CSV', filters: 'Фильтры', dateFrom: 'Дата с', dateTo: 'Дата по', filterStatus: 'Статус', filterCustomer: 'Клиент', applyFilter: 'Фильтровать', exportSuccess: 'Отчет загружен в формате {format}', allStatuses: 'Все', noReports: 'Нет отчетов' },
  ai: { title: 'ИИ прогнозы', forecast: 'Прогноз спроса', anomalies: 'Аномалии', product: 'Товар', avgSales: 'Ср. мес. продажи', predicted: 'Прогноз', reorder: 'Рекомендуемый заказ', refreshForecast: 'Обновить прогноз', forecastChart: 'Прогноз спроса и текущий запас', currentStock: 'Текущий запас', predictedDemand: 'Прогнозируемый спрос', noForecasts: 'Нет прогнозов', noAnomalies: 'Нет аномалий' },
  admin: { title: 'Панель администратора', users: 'Пользователи', config: 'Конфигурация', logs: 'Журнал системы', addUser: 'Добавить пользователя', id: 'ID', email: 'Email', fullName: 'ФИО', role: 'Роль', createdDate: 'Дата создания', actions: 'Действия', changeRole: 'Изменить роль', changeRoleFor: 'Пользователь', newRole: 'Новая роль', noUsers: 'Нет пользователей', betaLabel: 'Значение Beta', companyName: 'Название компании', save: 'Сохранить', successCreated: 'Пользователь добавлен', successRole: 'Роль обновлена', successConfig: 'Конфигурация сохранена', error: 'Произошла ошибка', time: 'Время', user: 'Пользователь', action: 'Действие', details: 'Детали', noLogs: 'Нет записей журнала', password: 'Пароль', add: 'Добавить' },
  health: { status: 'Статус', uptime: 'Время работы', memory: 'Память', database: 'База данных' },
  notification: { success: 'Успешно', error: 'Ошибка' },
};
export default ru;
